import { begin, stop, type ChatReceiver } from './chat-stream.js';
import { loadThread, saveThread, sanitizeThreadId, type ThreadMessage } from '../navigation/browser-state.js';
import { navigate, render } from '../../app/router.js';

export function chatPage(routeId: string): string {
  const id = sanitizeThreadId(routeId) ?? crypto.randomUUID().replaceAll('-', '');
  if (!routeId) queueMicrotask(() => navigate(`/chat/${id}`));
  const messages = loadThread(id);
  queueMicrotask(() => wire(id, messages));
  return `<section class="chat-page"><header class="page-header page-header--chat"><p class="eyebrow">Локальный thread</p><h1>Чат с моделью</h1><p>История остаётся в браузере; доступ к модели происходит через серверный gateway.</p></header><section class="chat-panel"><div id="messages" class="message-list" aria-live="polite">${messages.map(message => messageMarkup(message)).join('') || '<p class="muted">Начните диалог.</p>'}</div><form id="composer" class="composer"><label class="visually-hidden" for="chat-prompt">Сообщение модели</label><textarea id="chat-prompt" class="composer__input" maxlength="16000" placeholder="Спросите модель…"></textarea><div class="composer__footer"><button class="ui-button" type="submit">Отправить</button><button id="stop" class="ui-button ui-button--danger" type="button">Остановить</button></div></form></section></section>`;
}
function messageMarkup(message: ThreadMessage): string { return `<article class="message message--${message.role}"><p class="message__label">${message.role === 'user' ? 'Вы' : 'Модель'}</p><p class="message__content">${message.content}</p></article>`; }
function wire(id: string, messages: ThreadMessage[]): void { const form=document.querySelector<HTMLFormElement>('#composer'); const input=document.querySelector<HTMLTextAreaElement>('#chat-prompt'); const list=document.querySelector<HTMLElement>('#messages'); document.querySelector('#stop')?.addEventListener('click', stop); form?.addEventListener('submit', event => { event.preventDefault(); const prompt=input?.value.trim(); if(!prompt || !input || !list) return; const user={id:crypto.randomUUID(),role:'user' as const,content:prompt,createdAt:new Date().toISOString()}; const assistant={id:crypto.randomUUID(),role:'assistant' as const,content:'',createdAt:new Date().toISOString()}; messages.push(user,assistant); input.value=''; list.innerHTML=messages.map(messageMarkup).join(''); const receiver:ChatReceiver={invokeMethodAsync:async(method,item)=>{ if(method==='OnChatEvent' && typeof item==='object' && item){ const event=item as {kind?:number;content?:string}; if(event.kind===0 && typeof event.content==='string') assistant.content+=event.content; if(event.kind===1) assistant.content='Ответ недоступен.'; list.innerHTML=messages.map(messageMarkup).join(''); } if(method==='OnChatCompleted'){saveThread(id,messages);} }}; begin({threadId:id,prompt},receiver); }); }
